from PyQt6 import QtWidgets, QtCore, QtGui


class UiAuthorWindow(object):  # Класс, задающий параметры окна "Об авторе"
    def _setup_ui_(self, author_window):
        author_window.setObjectName("mainWindow")
        author_window.resize(269, 311)
        author_window.setMinimumSize(QtCore.QSize(269, 311))
        author_window.setMaximumSize(QtCore.QSize(269, 311))
        self.central_widget = QtWidgets.QWidget(parent=author_window)
        self.central_widget.setObjectName("central_widget")
        self.label_photo = QtWidgets.QLabel(parent=self.central_widget)
        self.label_photo.setGeometry(QtCore.QRect(40, 10, 181, 141))
        self.label_photo.setText("")
        self.label_photo.setPixmap(QtGui.QPixmap("resources/photo.png"))
        self.label_photo.setObjectName("label_photo")
        self.label_author = QtWidgets.QLabel(parent=self.central_widget)
        self.label_author.setGeometry(QtCore.QRect(110, 160, 50, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_author.setFont(font)
        self.label_author.setObjectName("label_author")
        self.label_student = QtWidgets.QLabel(parent=self.central_widget)
        self.label_student.setGeometry(QtCore.QRect(40, 190, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_student.setFont(font)
        self.label_student.setObjectName("label_student")
        self.label_name = QtWidgets.QLabel(parent=self.central_widget)
        self.label_name.setGeometry(QtCore.QRect(40, 210, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_mail = QtWidgets.QLabel(parent=self.central_widget)
        self.label_mail.setGeometry(QtCore.QRect(40, 230, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_mail.setFont(font)
        self.label_mail.setObjectName("label_mail")
        self.exitButton = QtWidgets.QPushButton(parent=self.central_widget)
        self.exitButton.setGeometry(QtCore.QRect(44, 260, 181, 41))
        self.exitButton.setObjectName("exitButton")
        author_window.setCentralWidget(self.central_widget)

        self._retranslate_ui_(author_window)
        QtCore.QMetaObject.connectSlotsByName(author_window)
        self.exitButton.clicked.connect(author_window.close)

    def _retranslate_ui_(self, author_window):
        _translate = QtCore.QCoreApplication.translate
        author_window.setWindowTitle(_translate("author_window", "Об авторе"))
        self.label_author.setText(_translate("author_window", "Автор"))
        self.label_student.setText(_translate("author_window", "Студент группы "))
        self.label_name.setText(_translate("author_window", ""))
        self.label_mail.setText(_translate("author_window", ""))
        self.exitButton.setText(_translate("author_window", "Назад"))
