from PyQt6 import QtWidgets, QtCore, QtGui


class UiMainWindow(object):  # Класс, задающий параметры главного окна
    def _setup_ui_(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setGeometry(270, 50, 800, 659)
        main_window.setMinimumSize(800, 659)
        main_window.setMaximumSize(800, 659)
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_graph = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_graph.setGeometry(QtCore.QRect(40, 40, 451, 381))
        self.label_graph.setText("")
        self.label_graph.setObjectName("label_graph")
        self.tabWidget_functions = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget_functions.setGeometry(QtCore.QRect(540, 10, 251, 211))
        self.tabWidget_functions.setObjectName("tabWidget_functions")
        self.tab_standart = QtWidgets.QWidget()
        self.tab_standart.setObjectName("tab_standart")
        self.button_abs = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_abs.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.button_abs.setObjectName("button_abs")
        self.button_sqrt = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_sqrt.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.button_sqrt.setObjectName("button_sqrt")
        self.button_sq = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_sq.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.button_sq.setObjectName("button_sq")
        self.button_cube = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_cube.setGeometry(QtCore.QRect(100, 70, 75, 23))
        self.button_cube.setObjectName("button_cube")
        self.button_ln = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_ln.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.button_ln.setObjectName("button_ln")
        self.button_lg = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_lg.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.button_lg.setObjectName("button_lg")
        self.button_exp = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_exp.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.button_exp.setObjectName("button_exp")
        self.button_log = QtWidgets.QPushButton(parent=self.tab_standart)
        self.button_log.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.button_log.setObjectName("button_log")
        self.tabWidget_functions.addTab(self.tab_standart, "")
        self.tab_trig = QtWidgets.QWidget()
        self.tab_trig.setObjectName("tab_trig")
        self.button_sin = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_sin.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.button_sin.setObjectName("button_sin")
        self.button_cos = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_cos.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.button_cos.setObjectName("button_cos")
        self.button_tg = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_tg.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.button_tg.setObjectName("button_tg")
        self.button_ctg = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_ctg.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.button_ctg.setObjectName("button_ctg")
        self.button_asin = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_asin.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.button_asin.setObjectName("button_asin")
        self.button_acos = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_acos.setGeometry(QtCore.QRect(100, 40, 75, 23))
        self.button_acos.setObjectName("button_acos")
        self.button_atg = QtWidgets.QPushButton(parent=self.tab_trig)
        self.button_atg.setGeometry(QtCore.QRect(100, 70, 75, 23))
        self.button_atg.setObjectName("button_atg")
        self.tabWidget_functions.addTab(self.tab_trig, "")
        self.groupBox_field = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_field.setGeometry(QtCore.QRect(100, 430, 201, 171))
        self.groupBox_field.setObjectName("groupBox_field")
        self.label_borders = QtWidgets.QLabel(parent=self.groupBox_field)
        self.label_borders.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.label_borders.setObjectName("label_borders")
        self.lineEdit_border_x1 = QtWidgets.QLineEdit(parent=self.groupBox_field)
        self.lineEdit_border_x1.setGeometry(QtCore.QRect(40, 60, 31, 20))
        self.lineEdit_border_x1.setObjectName("lineEdit_border_x1")
        self.lineEdit_border_x2 = QtWidgets.QLineEdit(parent=self.groupBox_field)
        self.lineEdit_border_x2.setGeometry(QtCore.QRect(100, 60, 31, 20))
        self.lineEdit_border_x2.setObjectName("lineEdit_border_x2")
        self.label_x1 = QtWidgets.QLabel(parent=self.groupBox_field)
        self.label_x1.setGeometry(QtCore.QRect(20, 60, 21, 16))
        self.label_x1.setObjectName("label_x1")
        self.label_x2 = QtWidgets.QLabel(parent=self.groupBox_field)
        self.label_x2.setGeometry(QtCore.QRect(80, 60, 21, 16))
        self.label_x2.setObjectName("label_x2")
        self.label_step = QtWidgets.QLabel(parent=self.groupBox_field)
        self.label_step.setGeometry(QtCore.QRect(20, 90, 21, 16))
        self.label_step.setObjectName("label_step")
        self.label_dx = QtWidgets.QLabel(parent=self.groupBox_field)
        self.label_dx.setGeometry(QtCore.QRect(20, 120, 21, 16))
        self.label_dx.setObjectName("label_dx")
        self.step_lineEdit = QtWidgets.QLineEdit(parent=self.groupBox_field)
        self.step_lineEdit.setGeometry(QtCore.QRect(40, 120, 31, 20))
        self.step_lineEdit.setObjectName("step_lineEdit")
        self.groupBox_calc = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_calc.setGeometry(QtCore.QRect(410, 429, 381, 171))
        self.groupBox_calc.setObjectName("groupBox_calc")
        self.button_plus = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_plus.setGeometry(QtCore.QRect(30, 30, 41, 23))
        self.button_plus.setObjectName("button_plus")
        self.button_minus = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_minus.setGeometry(QtCore.QRect(30, 60, 41, 23))
        self.button_minus.setObjectName("button_minus")
        self.button_mult = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_mult.setGeometry(QtCore.QRect(30, 90, 41, 23))
        self.button_mult.setObjectName("button_mult")
        self.button_div = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_div.setGeometry(QtCore.QRect(30, 120, 41, 23))
        self.button_div.setObjectName("button_div")
        self.button_one = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_one.setGeometry(QtCore.QRect(130, 30, 41, 23))
        self.button_one.setObjectName("button_one")
        self.button_four = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_four.setGeometry(QtCore.QRect(130, 60, 41, 23))
        self.button_four.setObjectName("button_four")
        self.button_seven = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_seven.setGeometry(QtCore.QRect(130, 90, 41, 23))
        self.button_seven.setObjectName("button_seven")
        self.button_two = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_two.setGeometry(QtCore.QRect(180, 30, 41, 23))
        self.button_two.setObjectName("button_two")
        self.button_five = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_five.setGeometry(QtCore.QRect(180, 60, 41, 23))
        self.button_five.setObjectName("button_five")
        self.button_eight = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_eight.setGeometry(QtCore.QRect(180, 90, 41, 23))
        self.button_eight.setObjectName("button_eight")
        self.button_three = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_three.setGeometry(QtCore.QRect(230, 30, 41, 23))
        self.button_three.setObjectName("button_three")
        self.button_six = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_six.setGeometry(QtCore.QRect(230, 60, 41, 23))
        self.button_six.setObjectName("button_six")
        self.button_nine = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_nine.setGeometry(QtCore.QRect(230, 90, 41, 23))
        self.button_nine.setObjectName("button_nine")
        self.button_zero = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_zero.setGeometry(QtCore.QRect(180, 120, 41, 23))
        self.button_zero.setObjectName("button_zero")
        self.button_grade = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_grade.setGeometry(QtCore.QRect(320, 30, 41, 23))
        self.button_grade.setObjectName("button_grade")
        self.button_dot = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_dot.setGeometry(QtCore.QRect(320, 120, 41, 23))
        self.button_dot.setObjectName("button_dot")
        self.button_brack_l = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_brack_l.setGeometry(QtCore.QRect(320, 60, 41, 23))
        self.button_brack_l.setObjectName("button_brack_l")
        self.button_brack_r = QtWidgets.QPushButton(parent=self.groupBox_calc)
        self.button_brack_r.setGeometry(QtCore.QRect(320, 90, 41, 23))
        self.button_brack_r.setObjectName("button_brack_r")
        self.button_author = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_author.setGeometry(QtCore.QRect(20, 610, 75, 23))
        self.button_author.setObjectName("button_author")
        self.button_program = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_program.setGeometry(QtCore.QRect(115, 610, 85, 23))
        self.button_program.setObjectName("button_program")
        self.button_help = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(220, 610, 75, 23))
        self.button_help.setObjectName("button_help")
        self.button_error = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_error.setGeometry(QtCore.QRect(410, 610, 150, 23))
        self.button_error.setObjectName("button_error")
        self.button_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(690, 610, 75, 23))
        self.button_exit.setObjectName("button_exit")
        self.lineEdit_formula = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_formula.setGeometry(QtCore.QRect(50, 10, 431, 20))
        self.lineEdit_formula.setObjectName("lineEdit_formula")
        self.label_func = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_func.setGeometry(QtCore.QRect(10, 10, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_func.setFont(font)
        self.label_func.setObjectName("label_func")
        self.button_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(490, 10, 30, 20))
        self.button_add.setObjectName("button_add")
        self.button_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(671, 414, 120, 20))
        self.button_clear.setObjectName("button_clear")
        self.funclistWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.funclistWidget.setGeometry(QtCore.QRect(540, 240, 251, 171))
        self.funclistWidget.setObjectName("funclistWidget")
        self.label_list = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_list.setGeometry(QtCore.QRect(540, 225, 131, 12))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_list.setFont(font)
        self.label_list.setObjectName("label_list")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(parent=self.menubar)
        self.file.setObjectName("file")
        main_window.setMenuBar(self.menubar)
        self.open = QtGui.QAction(parent=main_window)
        self.open.setObjectName("open")
        self.save = QtGui.QAction(parent=main_window)
        self.save.setObjectName("save")
        self.exp_graph = QtGui.QAction(parent=main_window)
        self.exp_graph.setObjectName("exp_graph")
        self.file.addAction(self.open)
        self.file.addAction(self.save)
        self.file.addAction(self.exp_graph)
        self.menubar.addAction(self.file.menuAction())

        self._retranslate_ui_(main_window)
        self.tabWidget_functions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def _retranslate_ui_(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Построение графиков функций"))
        self.button_abs.setText(_translate("main_window", "|x|"))
        self.button_sqrt.setText(_translate("main_window", "x^0.5"))
        self.button_sq.setText(_translate("main_window", "x^2"))
        self.button_cube.setText(_translate("main_window", "x^3"))
        self.button_ln.setText(_translate("main_window", "ln(x)"))
        self.button_lg.setText(_translate("main_window", "lg(x)"))
        self.button_log.setText(_translate("main_window", "log(x)"))
        self.button_exp.setText(_translate("main_window", "exp(x)"))
        self.tabWidget_functions.setTabText(self.tabWidget_functions.indexOf(self.tab_standart),
                                            _translate("main_window", "Станд. опер."))
        self.button_sin.setText(_translate("main_window", "sin(x)"))
        self.button_cos.setText(_translate("main_window", "cos(x)"))
        self.button_tg.setText(_translate("main_window", "tg(x)"))
        self.button_ctg.setText(_translate("main_window", "ctg(x)"))
        self.button_asin.setText(_translate("main_window", "arcsin(x)"))
        self.button_acos.setText(_translate("main_window", "arccos(x)"))
        self.button_atg.setText(_translate("main_window", "arctg(x)"))
        self.tabWidget_functions.setTabText(self.tabWidget_functions.indexOf(self.tab_trig),
                                            _translate("main_window", "Триг. функции"))
        self.groupBox_field.setTitle(_translate("main_window", "Настройки поля графика"))
        self.label_borders.setText(_translate("main_window", "Рассматриваемые границы"))
        self.label_x1.setText(_translate("main_window", "x1:"))
        self.label_x2.setText(_translate("main_window", "x2:"))
        self.label_step.setText(_translate("main_window", "Шаг "))
        self.label_dx.setText(_translate("main_window", "Δx:"))
        self.groupBox_calc.setTitle(_translate("main_window", "Цифры и операторы"))
        self.button_plus.setText(_translate("main_window", "+"))
        self.button_minus.setText(_translate("main_window", "-"))
        self.button_mult.setText(_translate("main_window", "*"))
        self.button_div.setText(_translate("main_window", "/"))
        self.button_one.setText(_translate("main_window", "1"))
        self.button_four.setText(_translate("main_window", "4"))
        self.button_seven.setText(_translate("main_window", "7"))
        self.button_two.setText(_translate("main_window", "2"))
        self.button_five.setText(_translate("main_window", "5"))
        self.button_eight.setText(_translate("main_window", "8"))
        self.button_three.setText(_translate("main_window", "3"))
        self.button_six.setText(_translate("main_window", "6"))
        self.button_nine.setText(_translate("main_window", "9"))
        self.button_zero.setText(_translate("main_window", "0"))
        self.button_grade.setText(_translate("main_window", "^"))
        self.button_dot.setText(_translate("main_window", "."))
        self.button_brack_l.setText(_translate("main_window", "("))
        self.button_brack_r.setText(_translate("main_window", ")"))
        self.button_author.setText(_translate("main_window", "Об авторе"))
        self.button_program.setText(_translate("main_window", "О программе"))
        self.button_error.setText(_translate("main_window", "Сообщить об ошибке"))
        self.button_help.setText(_translate("main_window", "Помощь"))
        self.button_exit.setText(_translate("main_window", "Выход"))
        self.label_func.setText(_translate("main_window", "F(x) ="))
        self.button_add.setText(_translate("main_window", "+"))
        self.label_list.setText(_translate("main_window", "Введенные функции"))
        self.file.setTitle(_translate("main_window", "Файл"))
        self.open.setText(_translate("main_window", "Открыть"))
        self.open.setShortcut(_translate("main_window", "Ctrl+O"))
        self.save.setText(_translate("main_window", "Сохранить как"))
        self.save.setShortcut(_translate("main_window", "Ctrl+S"))
        self.exp_graph.setText(_translate("main_window", "Экспорт графика"))
        self.exp_graph.setShortcut(_translate("main_window", "Ctrl+G"))
        self.button_clear.setText(_translate("main_window", "Очистить"))
